version: "3"
services:
  yojo-art-rs:
    build: .
    restart: always
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/cherrypick/files
      - ./.config:/cherrypick/.config:ro
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    networks:
      - internal_network
      - external_network
    env_file:
      - .config/tunnel.env
  web:
    image: ghcr.io/yojo-art/cherrypick:develop
    restart: always
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network
      - external_network
    # env_file:
    #   - .config/docker.env
    volumes:
      - ./files:/cherrypick/files
      - ./.config:/cherrypick/.config:ro

  redis:
    restart: always
    image: public.ecr.aws/bitnami/valkey:8.0
    networks:
      - internal_network
      - external_network
    volumes:
      - ./valkey:/data
    healthcheck:
      test: "valkey-cli ping"
      interval: 5s
      retries: 20
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
      - external_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
  s3:
    image: rustfs/rustfs:latest
    restart: always
    env_file:
      - .config/docker.env
    volumes:
      - ./rustfs/:/data
      - ./rustfs-logs/:/logs
    ports:
      - "19511:9001"
    networks:
      - internal_network
      - external_network
networks:
  internal_network:
    internal: true
  external_network:
